# Generated by Django 3.1 on 2020-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Blogsite', '0002_auto_20200811_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
