# Generated by Django 3.1 on 2020-08-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0003_auto_20200811_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='caption',
        ),
    ]
