# Generated by Django 3.1 on 2020-08-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Blogsite', '0004_remove_blog_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField(blank=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
