# Generated by Django 3.1 on 2020-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
