# Generated by Django 3.1 on 2020-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0007_auto_20200812_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
