# Generated by Django 3.1 on 2020-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0008_bloguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
