# Generated by Django 3.1 on 2020-08-16 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Blogsite', '0010_auto_20200816_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
