# Generated by Django 3.1 on 2020-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0012_auto_20200816_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Likes', to='Blogsite.BlogUser'),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='Views', to='Blogsite.BlogUser'),
        ),
    ]
