# Generated by Django 3.1 on 2020-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0013_auto_20200906_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Blogsite.BlogUser'),
        ),
        migrations.AddField(
            model_name='blog',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='Blogsite.BlogUser'),
        ),
    ]
