# Generated by Django 3.1 on 2020-09-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsite', '0014_auto_20200907_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='following',
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='Blogsite.BlogUser')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to='Blogsite.BlogUser')),
            ],
        ),
    ]
